### ISSUE TITLE
Crash with v0.2.0

### ISSUE THREAD

**Issue by bulvara** [Skallwar/suckit#195]
I have been running `suckit https://cigeography.blogspot.com/ -i '.*\.png' -o .`:

_thread '<unnamed>' panicked at 'Failed to parse url: http://The POLISH AIR FORCE, ARMY AVIATION and NAVAL AVIATION BRIGADE | Error: invalid domain character', src/scraper.rs:193:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/scraper.rs:328:10_

**Comment by Skallwar** [comment]
Thanks for the report. We will investigate

**Comment by red0888** [comment]
same error for me on windows

**Comment by CamoCatX** [comment]
@red0888 This script does not support windows... That's your error! For more information, read. The README.md

**Comment by dream-1ab** [comment]
the problem is not related to windows platform. it is a bug in this program.

The problem is caused by invalid url from some html files.
here is the original code of `src/scraper.rs` `line:193`:

https://github.com/Skallwar/suckit/blob/f513cc541d0d20a54308448d638f2179431f9774/src/scraper.rs#L187-L220


look at line 195. the program is panic if url parse is failed. this is not necessary I think and skipping for the broken url is totally acceptable solution, so I had modified it something like this:

``` rust
        dom.find_urls_as_strings()
            .into_iter()
            .filter(|candidate| Scraper::should_visit(scraper, candidate))
            .for_each(|next_url| {
                let url_to_parse = Scraper::normalize_url(next_url.clone());

                let next_full_url = match url.join(url_to_parse.as_str()) {
                    Ok(url) => url,
                    Err(e) => {
/***********************OVER HERE********************/
                        warn!("Skipping failed url to parse: {} | Error: {}", next_url, e);
                        return;
/***********************OVER HERE********************/
                    },
                };

                let path = url_helper::to_path(&next_full_url, true);
                let path_no_fragments = url_helper::to_path(&next_full_url, false);

```

I have just skipped out the broken url to process.

**Comment by Skallwar** [comment]
@dream-1ab Could you make an PR out of your fix?

**Comment by dream-1ab** [comment]
this fix already PR by someone.
from here: [https://github.com/Skallwar/suckit/pull/240](https://github.com/Skallwar/suckit/pull/240)
