### ISSUE TITLE
Not a directory (os error 20) - Error while cloning wiki.raregamingdump.ca

### ISSUE THREAD

**Issue by 123jimenez99** [Skallwar/suckit#238]
Hey everyone, I encountered an issue while attempting to clone the wiki.raregamingdump.ca website for archiving purposes. Here's the error message I got:

```
2024-05-24 22:07:54.660954601 +00:00: [ERROR] Couldn't create wiki.raregamingdump.ca/index.php/other.7z: Is a directory (os error 21)
thread '<unnamed>' panicked at src/logger.rs:42:9:
Couldn't create wiki.raregamingdump.ca/index.php/other.7z: Is a directory (os error 21)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at src/scraper.rs:182:57:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at src/scraper.rs:182:57:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at src/scraper.rs:182:57:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at src/scraper.rs:182:57:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at src/scraper.rs:182:57:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at src/scraper.rs:182:57:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }

```
This this is the command I used: `suckit https://wiki.raregamingdump.ca -v -t5 -c -j 64`

Any insights or suggestions on how to resolve this would be greatly appreciated.

Cheers!

**Comment by Skallwar** [comment]
I think the issue occurs when you first download `a.com/b/c.html` and then you tried to download `a.com/b` because `a.com/b` has been created as a folder an now `suckit` is trying to write a file with the same name. I think there is an issue with the function that create a path from a given url

[Here](https://github.com/Skallwar/suckit/blob/f513cc541d0d20a54308448d638f2179431f9774/src/url_helper.rs#L10) IIRC.

I'm quite busy at the moment so I would appreciate any help on this

**Comment by 123jimenez99** [comment]
I'm afraid I can't help in that regard as I have no programming knowledge. In the end I managed to create a complete archive using the Browsertrix-Crawler Docker container. In any case, thanks for your support and I hope the best for your project!

**Comment by Skallwar** [comment]
I will leave it open as the issue is still there. Thanks for the feedback :)

**Comment by ipaqmaster** [comment]
Nice project. This happened to me today too.

I replaced the error!'s with warn!'s so I could continue archiving as much as possible (99.99%) without the program stopping itself. It would be nice if `--continue-on-error` was honored when hitting errors in `src/disk.rs` but this workaround has working well enough for my use case.

**Comment by Skallwar** [comment]
Hi @ipaqmaster 
> It would be nice if --continue-on-error was honored when hitting errors in src/disk.rs

Great idea. I don't have time for this but if you create a pull request I will have a look and merge it
